packages/Webkul/Installer/src/Database/Seeders/Attribute/AttributeOptionTableSeeder.php, packages/Webkul/Installer/src/Resources/lang/en/app.php
=> 11 add new xxl size category

packages/Webkul/Shop/src/Resources/views/checkout/onepage/address/form.blade.php
=> #17 enhance checkout zip to have a valid number, 5 digits

packages/Webkul/Installer/src/Database/Seeders/Attribute/AttributeOptionTableSeeder.php, packages/Webkul/Installer/src/Resources/lang/en/app.php
#10 
AttributeOptionTableSeeder is used, so it's necessary to reset the table first, then seed it again with the updated changes.
php artisan migrate:fresh
php artisan db:seed
Check the Color Categorues
=> #10 add new blue color category

packages/Webkul/Installer/src/Database/Seeders/Category/CategoryTableSeeder.php, packages/Webkul/Installer/src/Resources/lang/en/app.php
=> #36 add a new categories Summer and Winter Wear under Women category

packages/Webkul/Admin/src/Resources/assets/js/plugins/vee-validate.js, packages/Webkul/Core/src/Rules/PhoneNumber.php, packages/Webkul/Shop/src/Resources/views/customers/account/profile/edit.blade.php
=> feat: new phone validate

packages/Webkul/Shop/src/Resources/views/checkout/coupon.blade.php
=> feat: update coupon code input to require exactly 8 characters

.env.example
#46 
Added API Keys in Google Cloud.
Changed _.env_ and added credentials.
Login using a Google account.
=> #46 fix: google login

database/migrations/2025_02_27_004104_add_coupon_code_column_to_cart_rules_table.php, packages/Webkul/CartRule/src/Database/Migrations/2019_05_13_024322_create_cart_rule_channels_table.php, packages/Webkul/CartRule/src/Database/seeders/DatabaseSeeder.php, packages/Webkul/CartRule/src/Database/seeders/WelcomeCouponSeeder.php, packages/Webkul/Installer/src/Database/Seeders/DatabaseSeeder.php, packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php
=> 19 add a default coupon code with 30 discount with code welcome

packages/Webkul/Admin/src/Config/system.php, packages/Webkul/Installer/src/Resources/lang/en/app.php, packages/Webkul/Shop/src/Resources/lang/en/app.php, packages/Webkul/Shop/tests/Feature/HomePageTest.php
=> #39 modify-discount-value-30

packages/Webkul/Installer/src/Resources/lang/en/app.php
=> #12 update description product removing "winter" word

packages/Webkul/Installer/src/Database/Seeders/ProductTableSeeder.php
=> #8 modify arctic winter gloves

packages/Webkul/Installer/src/Resources/lang/en/app.php
=> #35 modify url summer wear

.env.example
=> feat: add mail

.env.example
=> fix: TIMEZONE

packages/Webkul/Installer/src/Database/Seeders/ProductTableSeeder.php
=> feat: add inventory records for product ID 12

packages/Webkul/Installer/src/Resources/lang/en/app.php
=> fix: fail is in men winter wear

.env.example, config/services.php, packages/Webkul/Shop/src/Http/Controllers/SubscriptionController.php, packages/Webkul/Shop/src/Resources/lang/en/app.php, packages/Webkul/Shop/src/Resources/views/components/layouts/footer/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/layouts/index.blade.php
=> feat : add recapcha

app/Console/Commands/createDatabaseCommand.php
=> #73 Add Artisan Command to Create Database in Laravel

packages/Webkul/Admin/src/Http/Controllers/Catalog/ProductController.php, packages/Webkul/Admin/src/Mail/Customer/DropPriceNotification.php, packages/Webkul/Marketing/src/Listeners/Product.php, packages/Webkul/Product/src/Listeners/Product.php, packages/Webkul/Shop/src/Resources/views/emails/customers/price-drop.blade.php
=> 74 send email to customers when a wishlist product drops in price

packages/Webkul/Shop/src/Http/Controllers/API/ShipmentController.php, packages/Webkul/Shop/src/Routes/api.php
=> #87 implement crud api endpoints for shipment

packages/Webkul/Shop/src/Http/Controllers/API/CategoryController.php, packages/Webkul/Shop/src/Http/Middleware/Locale.php, packages/Webkul/Shop/src/Routes/api.php
=> #86 Implement CRUD API Endpoints for Category

packages/Webkul/Shop/src/Resources/lang/en/app.php, packages/Webkul/Shop/src/Resources/lang/es/app.php, packages/Webkul/Shop/src/Resources/views/home/about-us.blade.php
=> feat: add about-us #37

packages/Webkul/Shop/src/Http/Controllers/API/RefundController.php, packages/Webkul/Shop/src/Routes/api.php
=> feat: add  CRUD API Endpoints for Refund
